SELECT TOP (1000) [createdat]
     
      ,[side]
      ,[descliente]
      ,[comccy]
      ,[montocom]
      ,[px_sp]
      ,[px_cover]
      ,[venccy]
      ,[montoven]
      ,[tradedate]
      ,[valuedate]
      ,[accion]
      ,[estado]
      ,[solicitud]
      ,[monex_pxlast]
      ,[monex_pp]
      ,[ejecutivo]
      ,[dealer]
      ,[productotipo]
      ,[tradeid]
      ,[tiquetid]
  FROM [dbo].[fullblotter]
  order by [createdat] DESC