SELECT TOP (10) [tradeid]
      ,[timestamp]
      ,[action]
      ,[side]
      ,[ncliente]
      ,[descliente]
      ,[ccycom]
      ,[montocom]
      ,[px_sp]
      ,[ccyven]
      ,[montoven]
      ,[estado]
      ,[tradedate]
      ,[valuedate]
      ,[monex_pxlast]
      ,[monex_pp]
      ,[ejecutivo]
      ,[dealer]
      ,[px_cover]
      ,[productotipo]
      ,[segmento]
      ,[solicitud]
  FROM [dbo].[fxblotter.t]